// nextjs-base/components/swe-combobox/SweCombobox.tsx
"use client";

import React, { useMemo } from "react";
import {
  Chip,
  Avatar,
  Label,
  ListBoxRoot,
  ListBoxItem,
  SelectRoot,
  SelectTrigger,
  SelectValue,
  SelectIndicator,
  SelectPopover,
} from "@heroui/react";

/**
 * Chế độ hiển thị của Combobox
 */
export type ComboboxMode = "view" | "edit";

/**
 * Các loại kiểu dữ liệu hỗ trợ bởi Combobox
 */
export type ComboboxDataType = "text" | "date" | "number" | "tag" | "human";

/**
 * Cấu trúc đối tượng cho kiểu dữ liệu human
 */
export interface HumanItem {
  id: string | number;
  name: string;
  avatarUrl?: string;
  description?: string;
}

/**
 * Cấu trúc một Option trong Combobox
 */
export interface ComboboxOption {
  value: string | number;
  label: string;
  description?: string;
  avatarUrl?: string;
  tagColor?: "default" | "accent" | "success" | "warning" | "danger";
  raw?: any;
}

/**
 * Props cho thành phần SweCombobox
 *
 * @created_at 24/07/2026
 * @author txhoan
 */
export interface SweComboboxProps {
  /** Chế độ hiển thị: 'view' (gạch dưới kiểu Android) hoặc 'edit' (Combobox chọn) */
  mode?: ComboboxMode;
  /** Kiểu dữ liệu chứa bên trong Combobox: 'text' | 'date' | 'number' | 'tag' | 'human' */
  dataType?: ComboboxDataType;
  /** Giá trị hiện tại của Combobox */
  value?: string | number | null;
  /** Danh sách các options cho Combobox */
  options?: ComboboxOption[];
  /** Callback được gọi khi thay đổi giá trị */
  onChange?: (value: string | number | null, selectedOption?: ComboboxOption) => void;
  /** Văn bản gợi ý trong ô chọn */
  placeholder?: string;
  /** Tiêu đề (Label) của ô chọn */
  label?: string;
  /** Trạng thái vô hiệu hóa */
  isDisabled?: boolean;
  /** Thêm class CSS tùy chỉnh */
  className?: string;
  /** Chiều rộng tùy chỉnh (ví dụ: '300px', '100%', 250) */
  width?: string | number;
  /** Chiều cao tùy chỉnh (ví dụ: '40px', 38) */
  height?: string | number;
}

export interface ValueRendererProps {
  dataType: ComboboxDataType;
  selectedOption?: ComboboxOption;
  rawValue?: any;
  placeholder?: string;
}

/**
 * Helper component hiển thị nội dung theo từng `dataType`
 *
 * @created_at 24/07/2026
 * @author txhoan
 */
export const RenderTypedValue: React.FC<ValueRendererProps> = ({
  dataType,
  selectedOption,
  rawValue,
  placeholder = "Chưa chọn",
}) => {
  if (!selectedOption && rawValue === undefined) {
    return <span className="text-default-400 italic text-sm">{placeholder}</span>;
  }

  const displayLabel = selectedOption ? selectedOption.label : String(rawValue ?? "");

  switch (dataType) {
    case "human": {
      const name = selectedOption?.label ?? rawValue?.name ?? displayLabel;
      const avatarUrl = selectedOption?.avatarUrl ?? rawValue?.avatarUrl;
      const description = selectedOption?.description ?? rawValue?.description;
      const initial = name ? String(name).charAt(0).toUpperCase() : "?";

      return (
        <div className="flex items-center gap-3 py-1">
          <Avatar size="sm" className="shrink-0">
            {avatarUrl && <Avatar.Image src={avatarUrl} />}
            <Avatar.Fallback>{initial}</Avatar.Fallback>
          </Avatar>
          <div className="flex flex-col text-left">
            <span className="text-sm font-medium text-default-900 leading-tight">
              {name}
            </span>
            {description && (
              <span className="text-xs text-default-500 leading-tight">
                {description}
              </span>
            )}
          </div>
        </div>
      );
    }

    case "tag": {
      const tagColor = selectedOption?.tagColor ?? "accent";
      return (
        <Chip
          color={tagColor}
          variant="soft"
          size="sm"
          className="font-medium"
        >
          {displayLabel}
        </Chip>
      );
    }

    case "date": {
      let dateString = displayLabel;
      try {
        const d = new Date(displayLabel);
        if (!isNaN(d.getTime())) {
          dateString = d.toLocaleDateString("vi-VN", {
            year: "numeric",
            month: "2-digit",
            day: "2-digit",
          });
        }
      } catch {
        // Fallback giữ nguyên chuỗi
      }
      return (
        <span className="text-sm font-mono text-default-800 bg-default-100 px-2 py-0.5 rounded">
          {dateString}
        </span>
      );
    }

    case "number": {
      const numVal = Number(displayLabel);
      const formattedNum = !isNaN(numVal) ? numVal.toLocaleString("vi-VN") : displayLabel;
      return (
        <span className="text-sm font-semibold text-primary-600 font-mono">
          {formattedNum}
        </span>
      );
    }

    case "text":
    default: {
      return (
        <span className="text-sm text-default-900 font-normal">
          {displayLabel}
        </span>
      );
    }
  }
};

/**
 * Thành phần SweCombobox hỗ trợ 2 chế độ View/Edit và 5 dạng dữ liệu (text, date, number, tag, human).
 *
 * Mode View: Hiển thị giá trị kèm đường kẻ gạch dưới (Android Material Input underline style).
 * Mode Edit: Hiển thị Combobox tiêu chuẩn cho phép tìm kiếm và lựa chọn options.
 *
 * @param props Thuộc tính và sự kiện truyền vào SweCombobox
 * @created_at 24/07/2026
 * @author txhoan
 */
const SweCombobox: React.FC<SweComboboxProps> = ({
  mode = "edit",
  dataType = "text",
  value,
  options = [],
  onChange,
  placeholder = "Chọn một tùy chọn",
  label,
  isDisabled = false,
  className = "",
  width,
  height,
}) => {
  const selectedOption = useMemo<ComboboxOption | undefined>(() => {
    if (value === null || value === undefined) return undefined;
    return options.find((opt) => String(opt.value) === String(value));
  }, [value, options]);

  const containerStyle = useMemo<React.CSSProperties>(() => {
    const style: React.CSSProperties = {};
    if (width !== undefined) {
      style.width = typeof width === "number" ? `${width}px` : width;
    }
    if (height !== undefined) {
      style.height = typeof height === "number" ? `${height}px` : height;
    }
    return style;
  }, [width, height]);

  const handleSelectionChange = (val: any) => {
    if (val === null || val === undefined) {
      if (onChange) onChange(null, undefined);
      return;
    }
    const opt = options.find((o) => String(o.value) === String(val));
    if (onChange) {
      onChange(opt ? opt.value : val, opt);
    }
  };

  // --- RENDERING CHẾ ĐỘ VIEW (Android Underline Style) ---
  if (mode === "view") {
    return (
      <div className={`flex flex-col gap-1 ${className}`} style={containerStyle}>
        {label && (
          <span className="text-xs font-semibold text-default-500 uppercase tracking-wider">
            {label}
          </span>
        )}
        <div
          className={`w-full min-h-9.5 border-b-2 border-default-300 py-1 flex items-center transition-colors ${isDisabled ? "opacity-50 cursor-not-allowed" : "hover:border-primary-500"
            }`}
        >
          <RenderTypedValue
            dataType={dataType}
            selectedOption={selectedOption}
            rawValue={value}
            placeholder={placeholder}
          />
        </div>
      </div>
    );
  }

  // --- RENDERING CHẾ ĐỘ EDIT (Standard Combobox/Select) ---
  return (
    <div className={`${className}`} style={containerStyle}>
      <SelectRoot
        placeholder={placeholder}
        isDisabled={isDisabled}
        value={value !== undefined && value !== null ? String(value) : null}
        onChange={handleSelectionChange}
      >
        {label && <Label>{label}</Label>}
        <SelectTrigger>
          <SelectValue>
            <RenderTypedValue
              dataType={dataType}
              selectedOption={selectedOption}
              rawValue={value}
              placeholder={placeholder}
            />
          </SelectValue>
          <SelectIndicator />
        </SelectTrigger>
        <SelectPopover>
          <ListBoxRoot>
            {options.map((opt) => (
              <ListBoxItem
                key={String(opt.value)}
                id={String(opt.value)}
                textValue={opt.label}
              >
                <RenderTypedValue
                  dataType={dataType}
                  selectedOption={opt}
                  rawValue={opt.value}
                />
              </ListBoxItem>
            ))}
          </ListBoxRoot>
        </SelectPopover>
      </SelectRoot>
    </div>
  );
};

export default SweCombobox;

// fe/nuxtjs-base/app/components/swe-combobox/SweCombobox.vue
<script setup lang="ts">
import { computed } from 'vue'
import {
  useSweCombobox,
  type ComboboxMode,
  type ComboboxDataType,
  type ComboboxOption
} from '~/composables/useSweCombobox'

/**
 * Props định nghĩa cho SweCombobox Component
 *
 * @created_at 28/07/2026
 * @author txhoan
 */
const props = withDefaults(
  defineProps<{
    /** Chế độ hiển thị: 'view' (gạch dưới style Android) hoặc 'edit' (ô chọn tiêu chuẩn) */
    mode?: ComboboxMode
    /** Kiểu dữ liệu chứa bên trong: 'text' | 'date' | 'number' | 'tag' | 'human' */
    dataType?: ComboboxDataType
    /** Giá trị hiện tại (v-model) */
    modelValue?: string | number | null
    /** Danh sách tùy chọn cho ô chọn */
    options?: ComboboxOption[]
    /** Văn bản gợi ý khi chưa chọn giá trị */
    placeholder?: string
    /** Tiêu đề (Label) của ô chọn */
    label?: string
    /** Trạng thái vô hiệu hóa */
    disabled?: boolean
    /** Class CSS bổ sung */
    className?: string
    /** Chiều rộng tùy chỉnh (ví dụ: '300px', '100%', 250) */
    width?: string | number
    /** Chiều cao tùy chỉnh (ví dụ: '40px', 38) */
    height?: string | number
  }>(),
  {
    mode: 'edit',
    dataType: 'text',
    modelValue: null,
    options: () => [],
    placeholder: undefined,
    label: undefined,
    disabled: false,
    className: '',
    width: undefined,
    height: undefined
  }
)

/**
 * Emits định nghĩa các sự kiện phát ra từ SweCombobox
 */
const emit = defineEmits<{
  (e: 'update:modelValue', value: string | number | null): void
  (e: 'change', value: string | number | null, selectedOption?: ComboboxOption): void
}>()

const { t } = useI18n()
const { formatDate, formatNumber, findSelectedOption, getInitialLetter } = useSweCombobox()

/**
 * Placeholder hiển thị đa ngôn ngữ
 */
const displayPlaceholder = computed(() => {
  return props.placeholder || t('combobox.select_option')
})

/**
 * Option được chọn hiện tại dựa trên modelValue
 */
const selectedOption = computed(() => {
  return findSelectedOption(props.modelValue, props.options)
})

/**
 * Style tùy chỉnh cho chiều rộng và chiều cao container
 */
const containerStyle = computed(() => {
  const style: Record<string, string> = {}
  if (props.width !== undefined) {
    style.width = typeof props.width === 'number' ? `${props.width}px` : props.width
  }
  if (props.height !== undefined) {
    style.height = typeof props.height === 'number' ? `${props.height}px` : props.height
  }
  return style
})

/**
 * Xử lý khi người dùng chọn tùy chọn trong Edit mode
 */
const handleSelectChange = (opt: ComboboxOption | null) => {
  const newValue = opt ? opt.value : null
  emit('update:modelValue', newValue)
  emit('change', newValue, opt || undefined)
}
</script>

<template>
  <!-- === CHẾ ĐỘ VIEW (Android Underline Style) === -->
  <div
    v-if="mode === 'view'"
    class="flex flex-col gap-1"
    :class="className"
    :style="containerStyle"
  >
    <span
      v-if="label"
      class="text-xs font-semibold text-gray-500 uppercase tracking-wider"
    >
      {{ label }}
    </span>
    <div
      class="w-full min-h-[38px] border-b-2 border-gray-300 py-1 flex items-center transition-colors"
      :class="disabled ? 'opacity-50 cursor-not-allowed' : 'hover:border-primary-500'"
    >
      <!-- Chưa chọn giá trị -->
      <span
        v-if="!selectedOption && (modelValue === null || modelValue === undefined)"
        class="text-gray-400 italic text-sm"
      >
        {{ displayPlaceholder }}
      </span>

      <!-- Render Kiểu Human -->
      <template v-else-if="dataType === 'human'">
        <div class="flex items-center gap-3 py-0.5">
          <UAvatar
            :src="selectedOption?.avatarUrl"
            :alt="selectedOption?.label || String(modelValue)"
            :text="getInitialLetter(selectedOption?.label || String(modelValue))"
            size="sm"
          />
          <div class="flex flex-col text-left">
            <span class="text-sm font-medium text-gray-900 leading-tight">
              {{ selectedOption?.label || modelValue }}
            </span>
            <span
              v-if="selectedOption?.description"
              class="text-xs text-gray-500 leading-tight"
            >
              {{ selectedOption.description }}
            </span>
          </div>
        </div>
      </template>

      <!-- Render Kiểu Tag -->
      <template v-else-if="dataType === 'tag'">
        <UBadge
          :color="selectedOption?.tagColor || 'primary'"
          variant="soft"
          size="sm"
          class="font-medium"
        >
          {{ selectedOption?.label || modelValue }}
        </UBadge>
      </template>

      <!-- Render Kiểu Date -->
      <template v-else-if="dataType === 'date'">
        <span class="text-sm font-mono text-gray-800 bg-gray-100 px-2 py-0.5 rounded">
          {{ formatDate(selectedOption?.label || String(modelValue)) }}
        </span>
      </template>

      <!-- Render Kiểu Number -->
      <template v-else-if="dataType === 'number'">
        <span class="text-sm font-semibold text-primary-600 font-mono">
          {{ formatNumber(selectedOption?.label || String(modelValue)) }}
        </span>
      </template>

      <!-- Render Kiểu Text -->
      <template v-else>
        <span class="text-sm text-gray-900 font-normal">
          {{ selectedOption?.label || modelValue }}
        </span>
      </template>
    </div>
  </div>

  <!-- === CHẾ ĐỘ EDIT (Standard Combobox / USelectMenu) === -->
  <div
    v-else
    class="flex flex-col gap-1"
    :class="className"
    :style="containerStyle"
  >
    <label
      v-if="label"
      class="text-xs font-semibold text-gray-700 uppercase tracking-wider"
    >
      {{ label }}
    </label>

    <USelectMenu
      :model-value="selectedOption"
      :items="options"
      :disabled="disabled"
      :placeholder="displayPlaceholder"
      option-attribute="label"
      value-attribute="value"
      class="w-full"
      @update:model-value="handleSelectChange"
    >
      <!-- Custom Display Slot khi được chọn -->
      <template #default="{ modelValue: current }">
        <span
          v-if="!current"
          class="text-gray-400 italic text-sm"
        >
          {{ displayPlaceholder }}
        </span>
        <template v-else-if="dataType === 'human'">
          <div class="flex items-center gap-2">
            <UAvatar
              :src="current.avatarUrl"
              :alt="current.label"
              :text="getInitialLetter(current.label)"
              size="2xs"
            />
            <span class="text-sm font-medium text-gray-900">{{ current.label }}</span>
          </div>
        </template>
        <template v-else-if="dataType === 'tag'">
          <UBadge
            :color="current.tagColor || 'primary'"
            variant="soft"
            size="xs"
          >
            {{ current.label }}
          </UBadge>
        </template>
        <template v-else-if="dataType === 'date'">
          <span class="text-sm font-mono text-gray-800">
            {{ formatDate(current.label) }}
          </span>
        </template>
        <template v-else-if="dataType === 'number'">
          <span class="text-sm font-semibold text-primary-600 font-mono">
            {{ formatNumber(current.label) }}
          </span>
        </template>
        <template v-else>
          <span class="text-sm text-gray-900">{{ current.label }}</span>
        </template>
      </template>

      <!-- Custom Item Slot danh sách các tùy chọn trong Dropdown -->
      <template #item="{ item }">
        <template v-if="dataType === 'human'">
          <div class="flex items-center gap-3 py-1">
            <UAvatar
              :src="item.avatarUrl"
              :alt="item.label"
              :text="getInitialLetter(item.label)"
              size="xs"
            />
            <div class="flex flex-col text-left">
              <span class="text-sm font-medium text-gray-900 leading-tight">
                {{ item.label }}
              </span>
              <span
                v-if="item.description"
                class="text-xs text-gray-500 leading-tight"
              >
                {{ item.description }}
              </span>
            </div>
          </div>
        </template>
        <template v-else-if="dataType === 'tag'">
          <UBadge
            :color="item.tagColor || 'primary'"
            variant="soft"
            size="sm"
          >
            {{ item.label }}
          </UBadge>
        </template>
        <template v-else-if="dataType === 'date'">
          <span class="text-sm font-mono">
            {{ formatDate(item.label) }}
          </span>
        </template>
        <template v-else-if="dataType === 'number'">
          <span class="text-sm font-semibold text-primary-600 font-mono">
            {{ formatNumber(item.label) }}
          </span>
        </template>
        <template v-else>
          <div class="flex flex-col">
            <span class="text-sm text-gray-900">{{ item.label }}</span>
            <span
              v-if="item.description"
              class="text-xs text-gray-500"
            >
              {{ item.description }}
            </span>
          </div>
        </template>
      </template>
    </USelectMenu>
  </div>
</template>
