// nuxtjs-base/app/components/grid/DynamicGrid.vue
<!--
  Smart Container cho toàn bộ hệ thống Dynamic Grid (Nuxt 3 - Nuxt UI).
  Quản lý trạng thái thông qua useDynamicGrid, tích hợp Toolbar, Filter, Table.
  Hỗ trợ SSR fallback config/data tránh waterfall loading.

  @created_at 08/07/2026
  @author txhoan
-->
<script setup lang="ts">
import { useDynamicGrid } from '@/composables/useDynamicGrid'
import type {
  GridConfigResponse,
  GridDataResponse,
  GridDataItem,
  GridFilterValue
} from '@/types/grid'

const props = defineProps<{
  gridCode: string
  fallbackConfig?: GridConfigResponse
  fallbackData?: GridDataResponse
  showIndex?: boolean
  showSelectionCheckbox?: boolean
  hideHorizontalScroll?: boolean
  hideVerticalScroll?: boolean
  ui?: { wrapper?: string, toolbar?: string, filter?: string, table?: string }
}>()

const emit = defineEmits<{
  (e: 'actionSuccess', actionCode: string, result: unknown): void
  (e: 'rowClick', rowData: GridDataItem): void
  (e: 'selectionChange', selectedKeys: Set<string>): void
}>()

const {
  config,
  data,
  page,
  filters,
  selectedKeys,
  isLoading,
  error,
  refreshData
} = useDynamicGrid(props.gridCode, props.fallbackConfig, props.fallbackData)

const handleSelectionChange = (keys: Set<string>) => {
  selectedKeys.value = keys
  emit('selectionChange', keys)
}

const handleSearch = (newFilters: Record<string, GridFilterValue>) => {
  filters.value = { ...newFilters }
  page.value = 1
}
</script>

<template>
  <div
    class="flex flex-col gap-4 w-full"
    :class="ui?.wrapper"
  >
    <div
      v-if="isLoading && !config"
      class="flex items-center justify-center py-12"
    >
      <UIcon
        name="i-heroicons-arrow-path"
        class="w-8 h-8 animate-spin text-primary-500"
      />
    </div>

    <div
      v-else-if="error"
      class="flex flex-col items-center gap-3 py-10 bg-red-50/50 dark:bg-red-950/20 rounded-xl border border-red-200 dark:border-red-900"
    >
      <UIcon
        name="i-heroicons-exclamation-triangle"
        class="w-8 h-8 text-red-500"
      />
      <p class="text-sm font-medium text-red-600 dark:text-red-400">
        {{ $t('grid.grid_config_error') }} {{ gridCode }}
      </p>
      <UButton
        color="primary"
        variant="soft"
        @click="refreshData"
      >
        {{ $t('grid.reset') }}
      </UButton>
    </div>

    <template v-else-if="config">
      <GridToolbar
        :title="config.title"
        :actions="config.actions.filter((a: any) => a.position === 'TOOLBAR')"
        :bulk-actions="config.actions.filter((a: any) => a.position === 'BULK')"
        :selected-keys="selectedKeys"
        :class="ui?.toolbar"
        @action-success="
          (code: any, res: any) => {
            refreshData()
            emit('actionSuccess', code, res)
          }
        "
      />

      <GridFilter
        v-if="config.filters && config.filters.length > 0"
        :filters="config.filters"
        :class="ui?.filter"
        @search="handleSearch"
      />

      <GridTable
        v-model:page="page"
        :columns="config.columns"
        :data="data?.items || []"
        :layout="config.layoutOptions"
        :show-index="showIndex"
        :show-selection-checkbox="showSelectionCheckbox"
        :selected-keys="selectedKeys"
        :total="data?.total || 0"
        :hide-horizontal-scroll="hideHorizontalScroll"
        :hide-vertical-scroll="hideVerticalScroll"
        :class="ui?.table"
        @selection-change="handleSelectionChange"
        @row-click="(row: any) => emit('rowClick', row)"
      />
    </template>
  </div>
</template>

// nextjs-base/components/swe-grid/DynamicGrid.tsx
/**
 * Component DynamicGrid (Smart Container) sử dụng HeroUI v3.2.1.
 * Kết nối tự động giữa cấu hình từ API/SSR, Toolbar, Filter và Table.
 *
 * @created_at 06/07/2026
 * @author txhoan
 */

"use client";

import { Spinner, Button } from "@heroui/react";

import { useDynamicGrid } from "@/hooks/useDynamicGrid";
import { useGridTranslations } from "@/hooks/useGridTranslations";
import {
  GridConfigResponse,
  GridDataResponse,
  GridDataItem,
} from "@/types/grid";

import GridFilter from "./components/GridFilter";
import GridTable from "./components/GridTable";
import GridToolbar from "./components/GridToolbar";

export interface DynamicGridProps {
  gridCode: string;
  fallbackConfig?: GridConfigResponse;
  fallbackData?: GridDataResponse;
  hideHorizontalScroll?: boolean;
  hideVerticalScroll?: boolean;
  /** Cho phép bật/tắt hiển thị cột checkbox chọn dòng */
  showSelectionCheckbox?: boolean;
  /** Cho phép bật/tắt hiển thị cột số thứ tự (STT) */
  showIndex?: boolean;
  className?: string;
  classNames?: {
    wrapper?: string;
    toolbar?: string;
    filter?: string;
    table?: string;
  };
  onActionSuccess?: (actionCode: string, result: unknown) => void;
  onRowClick?: (rowData: GridDataItem) => void;
  onSelectionChange?: (selectedKeys: Set<string>) => void;
}

export default function DynamicGrid({
  gridCode,
  fallbackConfig,
  fallbackData,
  hideHorizontalScroll = false,
  hideVerticalScroll = false,
  showSelectionCheckbox,
  showIndex,
  className = "",
  classNames = {},
  onActionSuccess,
  onRowClick,
  onSelectionChange,
}: DynamicGridProps) {
  const { t } = useGridTranslations();
  const {
    config,
    data,
    isLoading,
    error,
    setFilters,
    selectedKeys,
    setSelectedKeys,
    page,
    setPage,
    refreshData,
  } = useDynamicGrid(gridCode, fallbackConfig, fallbackData);

  /**
   * Xử lý sự kiện khi thay đổi danh sách các dòng được chọn trên bảng.
   * Cập nhật state nội bộ và kích hoạt callback ra bên ngoài (nếu có).
   *
   * @param keys - Tập hợp các ID bản ghi đang được chọn.
   */
  const handleSelectionChange = (keys: Set<string>) => {
    setSelectedKeys(keys);
    onSelectionChange?.(keys);
  };

  /**
   * Xử lý khi một hành động (Action / Bulk Action) thực thi API thành công.
   * Tự động làm mới dữ liệu Grid và kích hoạt callback thông báo ra ngoài.
   *
   * @param actionCode - Mã hành động vừa thực hiện thành công.
   * @param result - Kết quả trả về từ API.
   */
  const handleActionSuccess = (actionCode: string, result: unknown) => {
    refreshData();
    onActionSuccess?.(actionCode, result);
  };

  if (isLoading && !config) {
    return (
      <div className="flex w-full items-center justify-center py-12">
        <Spinner color="current" size="lg" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center gap-3 py-12 text-center">
        <p className="text-danger font-medium">
          {t("grid_config_error")} {gridCode}
        </p>
        <p className="text-sm text-default-500">{error.message}</p>
        <Button variant="primary" onPress={() => refreshData()}>
          {t("reset")}
        </Button>
      </div>
    );
  }

  if (!config) {
    return (
      <div className="py-8 text-center text-default-500">
        {t("grid_config_error")} {gridCode}
      </div>
    );
  }

  return (
    <div
      className={`flex flex-col gap-4 w-full ${className} ${classNames.wrapper || ""}`}
    >
      <GridToolbar
        actions={config.actions.filter((a) => a.position === "TOOLBAR")}
        bulkActions={config.actions.filter((a) => a.position === "BULK")}
        className={classNames.toolbar}
        selectedKeys={selectedKeys}
        title={config.title}
        onActionSuccess={handleActionSuccess}
      />

      {config.filters && config.filters.length > 0 && (
        <GridFilter
          className={classNames.filter}
          filters={config.filters}
          onSearch={setFilters}
        />
      )}

      <GridTable
        className={classNames.table}
        columns={config.columns}
        data={data?.items || []}
        hideHorizontalScroll={hideHorizontalScroll}
        hideVerticalScroll={hideVerticalScroll}
        layout={config.layoutOptions}
        page={page}
        selectedKeys={selectedKeys}
        showIndex={showIndex}
        showSelectionCheckbox={showSelectionCheckbox}
        total={data?.total || 0}
        onPageChange={setPage}
        onRowClick={onRowClick}
        onSelectionChange={handleSelectionChange}
      />
    </div>
  );
}
