// nextjs-base/components/grid/components/GridTable.tsx
/**
 * Component GridTable cho hệ thống Dynamic Grid (HeroUI v3.2.1).
 * Hiển thị bảng dữ liệu với tính năng chọn dòng, sticky header, phân trang và hỗ trợ cột STT.
 *
 * @created_at 06/07/2026
 * @author txhoan
 */

"use client";

import type { Selection } from "@heroui/react";

import { Table, Checkbox } from "@heroui/react";

import { useGridTranslations } from "@/hooks/useGridTranslations";
import {
  GridColumnConfig,
  LayoutOptions,
  GridDataItem,
  ColumnAlign,
} from "@/types/grid";

import GridPagination from "../../pagination/GridPagination";

import GridCell from "./GridCell";

export interface GridTableProps {
  columns: GridColumnConfig[];
  data: GridDataItem[];
  layout: LayoutOptions;
  selectedKeys: Set<string>;
  onSelectionChange: (keys: Set<string>) => void;
  onRowClick?: (rowData: GridDataItem) => void;
  page: number;
  onPageChange: (page: number) => void;
  total: number;
  hideHorizontalScroll?: boolean;
  hideVerticalScroll?: boolean;
  /** Cho phép bật/tắt render checkbox chọn dòng (mặc định ưu tiên theo layout.rowSelection) */
  showSelectionCheckbox?: boolean;
  /** Cho phép bật/tắt hiển thị cột số thứ tự (STT) (mặc định ưu tiên theo layout.showIndex) */
  showIndex?: boolean;
  className?: string;
}

export default function GridTable({
  columns,
  data,
  layout,
  selectedKeys,
  onSelectionChange,
  onRowClick,
  page,
  onPageChange,
  total,
  hideHorizontalScroll = false,
  hideVerticalScroll = false,
  showSelectionCheckbox,
  showIndex: propShowIndex,
  className = "",
}: GridTableProps) {
  const { t } = useGridTranslations();
  const visibleColumns = columns.filter((c) => !c.hidden);
  const showCheckbox = showSelectionCheckbox ?? layout.rowSelection ?? false;
  const showIndex = propShowIndex ?? layout.showIndex ?? false;
  const pageSize = layout.defaultPageSize || 10;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  const handleSelection = (keys: Selection) => {
    if (keys === "all") {
      onSelectionChange(new Set(data.map((d) => String(d.id))));
    } else {
      onSelectionChange(new Set(Array.from(keys).map(String)));
    }
  };

  return (
    <div className="flex flex-col gap-4 w-full">
      <Table className={className}>
        <Table.ScrollContainer
          className={[
            hideHorizontalScroll ? "overflow-x-hidden" : "",
            hideVerticalScroll ? "overflow-y-hidden" : "",
          ].join(" ")}
        >
          <Table.Content
            aria-label="Dynamic Grid Table"
            selectedKeys={selectedKeys}
            selectionMode={showCheckbox ? "multiple" : "none"}
            onSelectionChange={handleSelection}
          >
            <Table.Header className="bg-default-100 text-default-600 font-semibold">
              {showCheckbox ? (
                <Table.Column
                  key="selection_checkbox"
                  className="w-10 text-center"
                  id="selection_checkbox"
                >
                  <Checkbox slot="selection" />
                </Table.Column>
              ) : null}
              {showIndex ? (
                <Table.Column key="stt_index" isRowHeader id="stt_index">
                  {t("index")}
                </Table.Column>
              ) : null}
              {visibleColumns.map((col, idx) => (
                <Table.Column
                  key={col.field}
                  id={col.field}
                  isRowHeader={!showIndex && idx === 0}
                >
                  {col.header}
                </Table.Column>
              ))}
            </Table.Header>
            <Table.Body
              items={data}
              renderEmptyState={() => (
                <div className="p-6 text-center text-default-500">
                  {t("no_data")}
                </div>
              )}
            >
              {(item: GridDataItem) => {
                const itemIndex = data.indexOf(item);
                const sttNumber = (page - 1) * pageSize + itemIndex + 1;

                return (
                  <Table.Row
                    key={String(item.id)}
                    className={
                      onRowClick
                        ? "cursor-pointer hover:bg-default-50 transition-colors py-3"
                        : "hover:bg-default-50 transition-colors py-3"
                    }
                    id={String(item.id)}
                  >
                    {showCheckbox ? (
                      <Table.Cell className="text-center">
                        <Checkbox slot="selection" />
                      </Table.Cell>
                    ) : null}
                    {showIndex ? (
                      <Table.Cell className="text-center font-medium text-default-500">
                        {sttNumber}
                      </Table.Cell>
                    ) : null}
                    {visibleColumns.map((col) => (
                      <Table.Cell key={col.field}>
                        <GridCell
                          column={col}
                          rowData={item}
                          value={item[col.field]}
                        />
                      </Table.Cell>
                    ))}
                  </Table.Row>
                );
              }}
            </Table.Body>
          </Table.Content>
        </Table.ScrollContainer>
      </Table>

      {layout.pagination && total > 0 && (
        <GridPagination
          currentCount={data.length}
          page={page}
          total={total}
          totalPages={totalPages}
          onPageChange={onPageChange}
        />
      )}
    </div>
  );
}

// nuxtjs-base/app/components/grid/GridTable.vue
<!--
  Component bảng dữ liệu chính (GridTable) trong hệ thống Dynamic Grid (Nuxt 3 - Nuxt UI).
  Sử dụng UTable, hỗ trợ cột số thứ tự (STT) và phân trang độc lập qua GridPagination.

  @created_at 08/07/2026
  @author txhoan
-->
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { GridColumnConfig, LayoutOptions, GridDataItem } from '@/types/grid'

const { t } = useI18n()

const props = defineProps<{
  columns: GridColumnConfig[]
  data: GridDataItem[]
  layout: LayoutOptions
  showIndex?: boolean
  showSelectionCheckbox?: boolean
  selectedKeys: Set<string>
  total: number
  hideHorizontalScroll?: boolean
  hideVerticalScroll?: boolean
}>()

const emit = defineEmits<{
  (e: 'selectionChange', keys: Set<string>): void
  (e: 'rowClick', row: GridDataItem): void
}>()

const page = defineModel<number>('page', { default: 1 })

const showIndexCol = computed(() => props.showIndex ?? props.layout.showIndex ?? false)

const nuxtColumns = computed(() => {
  const cols: Array<Record<string, unknown>> = props.columns
    .filter(c => !c.hidden)
    .map(c => ({
      accessorKey: c.field,
      header: c.header
    }))

  if (showIndexCol.value) {
    cols.unshift({ accessorKey: '_stt', header: t('grid.index') })
  }
  return cols as unknown as undefined
})

const selectedRows = computed({
  get: () => props.data.filter(item => props.selectedKeys.has(String(item.id))),
  set: (rows: GridDataItem[]) => {
    emit('selectionChange', new Set(rows.map(r => String(r.id))))
  }
})
</script>

<template>
  <div class="flex flex-col gap-3 w-full">
    <div
      class="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 overflow-hidden"
      :class="[
        hideHorizontalScroll ? 'overflow-x-hidden' : '',
        hideVerticalScroll ? 'overflow-y-hidden' : ''
      ]"
    >
      <UTable
        v-model="selectedRows"
        :data="data"
        :columns="nuxtColumns"
        @select="(row: unknown) => emit('rowClick', row as GridDataItem)"
      >
        <template #_stt-cell="{ row }">
          <span class="text-xs font-semibold text-gray-500">
            {{ (page - 1) * (layout.defaultPageSize || 10) + data.indexOf(row as unknown as GridDataItem) + 1 }}
          </span>
        </template>

        <template
          v-for="col in columns"
          :key="col.field"
          #[`${col.field}-cell`]="{ row }"
        >
          <GridCell
            :column="col"
            :value="((row as unknown as Record<string, unknown>)[col.field])"
            :row-data="row as unknown as GridDataItem"
          />
        </template>
      </UTable>
    </div>

    <GridPagination
      v-if="layout.pagination && total > 0"
      v-model:page="page"
      :total="total"
      :current-count="data.length"
      :page-size="layout.defaultPageSize || 10"
    />
  </div>
</template>
